apiVersion: v1
kind: Service
metadata:
  name: fast-food-app-load-balancer-service
spec:
  selector:
    app: fast-food-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
